// import "./jsxStudy/jsx-study1.js";
// import "./jsxStudy/jsx-study2.js";
// import "./component-basic/first-component";
// import "./component-basic/animal-container";
// import "./component-basic/props-basic";
// import "./component-basic/props-more";
// import "./component-basic/props-children";
// import "./component-basic/SlotMachine";
// import "./component-intermediate/study-state";
// import "./component-intermediate/counter-demo";
// import "./component-intermediate/manipulate-list";
import "./component-intermediate/todo-app-demo";
